AppBundle\Entity\Message:
    type: entity
    table: null
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        text:
            type: text
        created:
            type: integer
    lifecycleCallbacks: {  }
    manyToOne:
        user:
            targetEntity: AppBundle\Entity\User
            cascade: [merge, detach]
            joinColumn:
                nullable: false